title: Zuwei Guo
author: Zuwei Guo
copyright: "Zuwei Guo"
description: Ph.D. Candidate in Computer Engineering at ASU. Robust, fair, and label-efficient AI; medical imaging; AMS design automation.
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar-external:
  - icon: <i class="fa-regular fa-envelope"></i>
    link: mailto:zguo32@asu.edu
  - icon: <i class="fa-regular fa-file-lines"></i>
    link: files/Zuwei-Guo-Resume.pdf
  - icon: <i class="fa-solid fa-graduation-cap"></i>
    link: https://scholar.google.com/citations?user=AHd948QAAAAJ&hl=en
  - icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0000-0002-5153-3865
  - icon: <i class="fa-brands fa-github-alt"></i>
    link: https://github.com/zuwei-guo
  - icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/zuwei/


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
